[project]
name = "docker-workshop"
version = "0.1.0"
description = "Data Engineering Zoomcamp for Docker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
]
